# Generated by Django 4.2.4 on 2023-08-26 09:12

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_news_author_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
