# Generated by Django 4.2.4 on 2023-08-28 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_mypanel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyPanel',
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
