# Generated by Django 4.2.4 on 2023-08-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_geo', '0002_weathersummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weathersummary',
            options={'verbose_name': 'Сводка погоды', 'verbose_name_plural': 'Сводка погоды'},
        ),
    ]
